### ISSUE TITLE
No idea how to autoconvert `String': `"x"' (Z3::Exception)

### ISSUE THREAD

**Issue by Unihedro** [taw/z3#11]
I'm trying to solve https://projecteuler.net/problem=39 with this. Not exactly important, no need to click into the link if you can't be bothered. Here's my code (which finds pythagorean triples summing to 120) trying to understand the library which might demonstrate something interesting:

```ruby
require 'z3'

z3=Z3::Solver.new
x=Z3.Int("x")
y=Z3.Int("y")
z=Z3.Int("z")
z3.assert Z3.And(*[x,y,z].map{|v|v > 0}, x<y, y<z)
z3.assert x**2+y**2==z**2
z3.assert x+y+z==120
z3.assert x>0
while z3.satisfiable?
vx=0
z3.model.each{|x,y|p "#{x}=#{y}"
vx=y.to_i if x=="x"}
z3.pop
z3.assert x>vx
end
```

The problem is that on `vx=y.to_i if x=="x"`, the `x` here is apparently `Int<x>`, so trying to compare if it is the x variable without calling `.to_s` first will not work. I get:

```
/home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/expr/expr.rb:41:in `sort_for_const': No idea how to autoconvert `String': `"x"' (Z3::Exception)
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/expr/expr.rb:26:in `block in coerce_to_same_sort'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/expr/expr.rb:26:in `map'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/expr/expr.rb:26:in `coerce_to_same_sort'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/expr/expr.rb:99:in `Eq'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/expr/expr.rb:16:in `=='
	from 39.rb:14:in `block in <main>'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/model.rb:49:in `block in each'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/model.rb:45:in `each'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/model.rb:45:in `each'
	from uniscript:13:in `<main>'
```

Recall that I have set `x=Z3.Int("x")`, so now my next attempt at fixing the loop:

```ruby
z3.model.each{|k,v|p "#{k}=#{v}"
vx=v.to_i if k==x}
```

This kind of works, I get a different exception on the `.pop` line:

```
/home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/exception.rb:22:in `block in <module:Z3>': Z3 library failed with error Z3_IOB (Z3::Exception)
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/low_level_auto.rb:2017:in `Z3_solver_pop'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/low_level_auto.rb:2017:in `solver_pop'
	from /home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/solver.rb:17:in `pop'
	from uniscript:15:in `<main>'
```

which I could fix afterwards, but the problem is `k==x` will always be truthy, because `k` (also `x`, now that I think about it) extending to `==` will always be some "comparable rule", which to the ruby engine is a truthy value.

**Proposition: I would like a way to check the identity of an expr**, something like `Z3.ExprEq(x, y)` which tells if `x` and `y` are the same expr, without resorting to something hacky like `.eql?` and trusting the same object is reused

(Note: the current best workaround is `k.to_s=="x"`, which is not very intuitive or clean IMO)

**Comment by taw** [comment]
> without resorting to something hacky like `.eql?` and trusting the same object is reused

Right, so on native side object reuse is actually hard API guarantee. `Z3_is_eq_ast` API just checks it's same object. But we don't do interning of ruby objects, so `.eql?` should check that `_ast == other._ast` .

**Comment by taw** [comment]
Updated gem published. `.eql?` and `.hash` should now work on all AST objects.
