### ISSUE TITLE
RFC: "Satisfiability unknown" exception in .satisfiable? is not necessary

### ISSUE THREAD

**Issue by Unihedro** [taw/z3#12]
My program brute forces all pythagorean triples for `x+y+z=1..1000`, which is not very fast. It seems running out of memory (or really anything that causes `.check` to return `:unknown` will also cause the solver to crash as satisfiability unknown, at around `Bool<((x + y) + z) = 558>`:

``/home/unihedron/.rvm/gems/ruby-2.4.1/gems/z3-0.0.20181126/lib/z3/solver.rb:44:in `satisfiable?': Satisfiability unknown (Z3::Exception)``

Re-running the program (but manually check for `solver.check == :sat` while trapping `solver.check` to print for debugging (and waiting another ~10 minutes (lol)) reveals that it does return `:unknown` sometimes (even if, that was put as the parameter to a new instance of running the program, and correctly returns when there's... more memory? idk)

I don't believe that it's necessary to throw an exception, and as the C API Z3_solver_check docs says:

>The function Z3_solver_get_model retrieves a model if the assertions is satisfiable (i.e., the result is Z3_L_TRUE) and model construction is enabled. **Note that if the call returns Z3_L_UNDEF**, Z3 does not ensure that calls to Z3_solver_get_model succeed and **any models produced in this case are not guaranteed to satisfy the assertions.**

this implies, to me, that `:unknown` is a normal case and handling it should still be permitted normally (with undefined behaviour in mind) and treated as just false instead of throwing an exception, since the convention of `method_name?` methods just return a boolean.

(Now I have manually handled it with: `when :unknown; puts "redoing..."; redo else` by handling program flow based on the value of `check` myself.)

I think it should be made either 1. to be more obvious that the method can throw an exception, or 2. only to return booleans without throwing.

**Comment by taw** [comment]
For most kinds of problems you'll throw at Z3, satisfiability `unknown` basically indicates some coding error, that's why I'm providing convenience API with `satisfiable?` / `unsatisfiable?`.

Quietly turning `:unknown` into `:sat` / `:unsat` is just recipe for application bugs.

For finite models (booleans, bit vectors, floats, _generally_ restricted integers used with just common operatons) Z3 is never supposed to return `:unknown`, and if you got it, you probably messed up the formulas somehow.

If you really need to handle 3 outcomes, you should do `case solver.check`.

If you need to debug surprise exceptions, I recommend [`pry-rescue`](https://github.com/ConradIrwin/pry-rescue).

I tried to code this problem in two ways, it's very slow but uses very little memory and doesn't know any `:unknown`s so far:

```
#!/usr/bin/env ruby

require "z3"

x, y, z = Z3.Int(%w"x y z")
solver = Z3::Solver.new
solver.assert (x >= 1) & (x <= 1000)
solver.assert (y >= 1) & (y <= 1000)
solver.assert (z >= 1) & (z <= 1000)
solver.assert y >= x # don't print duplicates with x/y switched
solver.assert x*x + y*y == z*z

# Just simple loop and keep adding assertions to it
while solver.satisfiable?
  p solver.model
  solver.assert !solver.model
end
```

Another:

```
#!/usr/bin/env ruby

require "z3"

x, y, z = Z3.Int(%w"x y z")
solver = Z3::Solver.new
solver.assert (x >= 1) & (x <= 1000)
solver.assert (y >= 1) & (y <= 1000)
solver.assert (z >= 1) & (z <= 1000)
solver.assert y >= x # don't print duplicates with x/y switched
solver.assert x*x + y*y == z*z

# Solve for every x separately to avoid making conjunction crazy big
(1..1000).each do |vx|
  solver.push
  solver.assert x == vx

  while solver.satisfiable?
    p solver.model
    solver.assert !solver.model
  end

  solver.pop
end
```

**Comment by Unihedro** [comment]
I think I have ran into a bug specific to my build. Which might be because it took me an hour to build z3 since I'm on ubuntu 14.04 and public libz3-dev builds have only started since 16.06. You can try running it though. This is what I get:

```
"x=84"
"y=245"
"z=259"
[Bool<and(x < y, y < z)>, Bool<((x ^ 2) + (y ^ 2)) = (z ^ 2)>, Bool<((x + y) + z) = 588>, Bool<84 < x>]
"x=147"
"y=196"
"z=245"
[Bool<and(x < y, y < z)>, Bool<((x ^ 2) + (y ^ 2)) = (z ^ 2)>, Bool<((x + y) + z) = 588>, Bool<147 < x>]
{:m=>5, :mv=>420, :pp=>588}
redoing...
redoing...
redoing...
```

My code:

```ruby
require 'z3'

z3=Z3::Solver.new
x=Z3.Int("x")
y=Z3.Int("y")
z=Z3.Int("z")
z3.assert Z3.And(x<y, y<z)
z3.assert x**2+y**2==z**2
z3.push
m=5
mv=420
#{:m=>5, :mv=>420, :pp=>588}
(588..1000).each{|pp|
z3.assert x+y+z==pp
z3.push
z3.assert 0<x
c=0.step.find{case z3.check
when :sat
vx=0
z3.model.each{|k,v|p "#{k}=#{v}"
vx=v.to_i if k.to_s=="x"}
z3.pop
z3.push
z3.assert vx<x
p z3.assertions
false
when :unknown
puts "redoing..."
redo
else
true
end
}
(m=c
mv=pp)if c>m
p :m=>m,:mv=>mv,:pp=>pp
z3.pop
z3.pop
z3.push
}
p m
```

Seems that at high (also happens to a few p values at ~600) values the way I loop to pop/push seems to be causing it to throw unknown errors. If I start with a clean solver and throw in the same constraints it will `:unsat` normally.

**Comment by taw** [comment]
It's Z3 limitation, I'd recommend using `x*x` not `x**2`, it will perform a lot better.

**Comment by taw** [comment]
Closing this unless you want to do something else about it.
