### ISSUE TITLE
can't require z3

### ISSUE THREAD

**Issue by HimenoTowa** [taw/z3#16]
I can't require z3 and don't know why

C:\Users\asus>irb
irb(main):001:0> require 'z3'

There is the log

Traceback (most recent call last):
       15: from D:/Ruby26-x64/bin/irb.cmd:31:in `<main>'
       14: from D:/Ruby26-x64/bin/irb.cmd:31:in `load'
       13: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       12: from (irb):1
       11: from D:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
       10: from D:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        9: from D:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
        8: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/z3-0.0.20181229/lib/z3.rb:5:in `<top (required)>'
        7: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/z3-0.0.20181229/lib/z3.rb:5:in `require_relative'
        6: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/z3-0.0.20181229/lib/z3/very_low_level.rb:4:in `<top (required)>'
        5: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/z3-0.0.20181229/lib/z3/very_low_level.rb:5:in `<module:Z3>'
        4: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/z3-0.0.20181229/lib/z3/very_low_level.rb:7:in `<module:VeryLowLevel>'
        3: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
        2: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `map'
        1: from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib'
)oadError (Could not open library 'z3': �Ҳ���ָ����ģ�顣

**Comment by taw** [comment]
The gem needs Z3 library installed, and I have no idea how to do that on Windows.

**Comment by taw** [comment]
Did you figure it out?

**Comment by taw** [comment]
Closing since I have no idea what to do with it.
