### ISSUE TITLE
Wrong model for installation dependency

### ISSUE THREAD

**Issue by tcsunhao** [taw/z3#20]
If we have 
```ruby
a = Z3.Bool('a')
b = Z3.Bool('b')
c = Z3.Bool('c')
d = Z3.Bool('d')
e = Z3.Bool('e')
f = Z3.Bool('f')
g = Z3.Bool('g')
z = Z3.Bool('z')
solver.assert a
solver.assert Z3.And(Z3::Implies(a, Z3.And(b,c,z)))
solver.assert Z3::Implies(d,Z3.And(e, g))
solver.assert d == Z3.False
if solver.check
  model = solver.model
  model.each do |var, value|
    if value.to_b
      p var
    end
  end
end
```

I want to get installation dependency for a, which shall be only b,c,z, but it runs output as b,c,e,g,z.
Note, d depends on e,g, but d is not connected to a, which is just a noise.

The same codes of python z3 gets the wanted result
```python
a, b, c, d, e, f, g, z = Bools('a b c d e f g z')
q1 = And([Implies(a, dep) for dep in [b, c, z]])
q2 = Implies(d, And(e, g))

s = Solver()
s.add(a, q1, q2)
if s.check() == sat:
    m = s.model()
    r = [x.name() for x in m if is_true(m[x])]
    print("Install a:")
    print(r)
else:
    print("Not installable")
```

**Comment by taw** [comment]
* both models are correct, they fulfil all criteria you asked for
* you're passing slightly different assertions to both your programs
* if there are multiple possible answers, the one you get depends on exact assertions you passed, version of Z3 etc. This is what's causing you to get different answers
* below are Ruby program that gets assertions exactly how your Python program did; and Python program that gets assertions exactly how your Ruby program did. As you can see the answer you get depends on assertions not language
* if you want to optimize among multiple possible solutions, you need to use Z3::Optimize API, example here as well, or do it iteratively

Here's programs where you get output backwards to your examples:

```ruby
#!/usr/bin/env ruby

require "z3"

solver = Z3::Solver.new

a = Z3.Bool('a')
b = Z3.Bool('b')
c = Z3.Bool('c')
d = Z3.Bool('d')
e = Z3.Bool('e')
f = Z3.Bool('f')
g = Z3.Bool('g')
z = Z3.Bool('z')
solver.assert a
solver.assert Z3.And(*[b,c,z].map{|dep| Z3::Implies(a, dep)})
solver.assert Z3::Implies(d,Z3.And(e, g))
solver.assert d == Z3.False

if solver.check
  model = solver.model
  model.each do |var, value|
    if value.to_b
      p var
    end
  end
end
```

```python
#!/usr/bin/env python3

from z3 import *

a, b, c, d, e, f, g, z = Bools('a b c d e f g z')
q1 = And(Implies(a, And([b, c, z])))
q2 = Implies(d, And(e, g))

s = Solver()
s.add(a, q1, q2)

if s.check() == sat:
    m = s.model()
    r = [x.name() for x in m if is_true(m[x])]
    print("Install a:")
    print(r)
else:
    print("Not installable")
```

```
#!/usr/bin/env ruby

require "z3"

solver = Z3::Optimize.new

a = Z3.Bool('a')
b = Z3.Bool('b')
c = Z3.Bool('c')
d = Z3.Bool('d')
e = Z3.Bool('e')
f = Z3.Bool('f')
g = Z3.Bool('g')
z = Z3.Bool('z')
solver.assert a
solver.assert Z3.And(Z3::Implies(a, Z3.And(b,c,z)))
solver.assert Z3::Implies(d,Z3.And(e, g))
solver.assert d == Z3.False

p solver.assertions

[a,b,c,d,e,f,g,z].each do |dep|
  solver.assert_soft dep == Z3.False
end

if solver.check
  model = solver.model
  model.each do |var, value|
    if value.to_b
      p var
    end
  end
end
```

**Comment by tcsunhao** [comment]
Thanks very much @taw for this quick reply.

Sorry that I have made a mistake in above description, there shouldn't be such line 'solver.assert d == Z3.False' (I add this line to make sure that I get what I think is correct(as python did)). 

I am doing a complex dependency in my project, I need to analyze with Z3 to get the minimum model of dependency, I think in my case, even I don't add 'solver.assert d == Z3.False', then I shall also get result model as 'a b c z' because I don't assert d, I just imply d depends on e and g. d anyway shall not appear in the return model.

**Comment by taw** [comment]
The `solver.assert d == Z3.False` line isn't affecting the result.

This line that is different between your two programs, and is causing the difference:

```
solver.assert Z3.And(Z3::Implies(a, Z3.And(b,c,z))) # a=>(b and c and z)
q1 = And([Implies(a, dep) for dep in [b, c, z]]) # a=>b and a=>c and a=>z
```

If you need a specific one among solutions, you need to use Z3 Optimize, or call Z3 iteratively.

Z3 Solver does not guarantee anything about which valid solution it will choose. It tends to use 0s and falses by default, but this is not guaranteed.

**Comment by tcsunhao** [comment]
Thanks @taw, I am using Z3 Optimize with assert_soft suggested by you. Really Works.

**Comment by taw** [comment]
OK, closing it then.
