### ISSUE TITLE
Support % operator 

### ISSUE THREAD

**Issue by riffraff** [taw/z3#22]
Is there a reason to have `IntExpr#mod` but not the operator equivalent? 

Without it, we have the inconsistency that `Integer` does not support `.mod` while `IntExpr` does not support `%`, so you need to be careful of the order in which you put things when building expressions, which is a bit annoying.  

Also, Ruby allows using % with non-integer numbers, I am not sure this is the case for Z3, but we can still add it to `IntExpr` anyway.

I can do a PR, but AFAICT it's barely more than adding an alias in `int_expr.rb` :)

**Comment by taw** [comment]
The reason it's not there is that neither Z3 rem and Z3 mod match Ruby %.

```ruby
a,b,c = Z3.Int(%w[a b c])
solver = Z3::Solver.new
solver.assert Z3.And(a == 10, b == -3, c == a.mod(b))
solver.check # => :sat
solver.model[c] # => Int<1>
10 % -3 # => -2
```

Ruby % matches Z3 mod for positive right side, which is honestly the only valid use case, but I thought it would lead to some very difficult to debug errors if I just aliased them and it wasn't clear which % was happening.

**Comment by riffraff** [comment]
thanks for the reply, it seems the python situation would be the same but they opted to support it anyway

```
>>> import z3
>>> a,b,c = z3.Ints('a b c')
>>> solver = z3.Solver()
>>> solver.add(z3.And(a == 10, b == -3, c == a % b))
>>> solver.check()
sat
>>> solver.model()[c]
1
>>> 10 % -3
-2  
```

But I understand your rationale and so feel free to close this issue, thanks for the project!

**Comment by taw** [comment]
OK, I added % operator, since % negative is not really meaningful, and Python Z3 does the same.
