### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by ryannevell** [taw/z3#23]
It is possible to add a license file or header to this project to explain the terms in which it can be used? I'd love to be able to use this library at work, but without a license our legal team won't approve. For reference, this is what the Z3 library itself uses: https://github.com/Z3Prover/z3/blob/master/LICENSE.txt

**Comment by taw** [comment]
The gem is already tagged with license: MIT in metadata through z3.gemspec
(you can see it at https://rubygems.org/gems/z3 etc.), but I can put a license file as well.
