### ISSUE TITLE
Documentation is non-existent

### ISSUE THREAD

**Issue by Garrett-Bodley** [taw/z3#24]
I have been doing Advent of Code in Ruby and most people used Z3 for Day 24 Part 2.

I found this gem and figured I'd give it a try, but had a difficult time figuring out how to use it due to the non-existent documentation. The only resource I could find online was [a singular blog post](https://riffraff.info/2023/02/solving-advent-of-code-day-21-using-z3-and-ruby/) detailing how someone used it for AoC 2022. If I hadn't found that blog post I would have had no way of using the library.

It would help tremendously to have some snippets detailing how to use this gem. Z3 is a very powerful tool and it's great that people are working to expose advanced math tooling to Ruby users. Thank you for putting the work in to build this gem! I don't want your hard work to go to waste, and I think this gem would benefit greatly from clear documentation on how to install the gem and interface with the API

**Comment by taw** [comment]
The repo has quite a few examples - https://github.com/taw/z3/tree/master/examples
Mostly various logic puzzles.
