### ISSUE TITLE
Gem seems unable to solve Advent of Code 2023 Day 24 

### ISSUE THREAD

**Issue by Garrett-Bodley** [taw/z3#25]
I have been trying to use this gem to solve [Advent of Code Day 24](https://adventofcode.com/2023/day/24).

My friend implemented [a solution](https://github.com/p3achyjr/aoc/blob/main/2023/day24/part2.py) using a Python Z3 library.

I translated that logic [over to Ruby](https://gist.github.com/Garrett-Bodley/198b08f542e6ba29ff379c9761f68543).

The above code seems to give the correct answer for the provided [test input](https://gist.github.com/Garrett-Bodley/85951766e9d6a9f6f9d809ca3ee98650) but with some caveats. I get a correct answer, but only if I feed Z3 only 3 out of the 5 possible "stones". If I feed all 5 stones into Z3, it cannot finish computing an answer in a reasonable amount of time. 4 stones doesn't work either.

When I switch to the [actual input](https://gist.github.com/Garrett-Bodley/b83d6298b4fafe1e7abb237fd8901583) the gem seems unable to solve the system. This holds true even if I feed it only 3 stones. I tried changing which 3 stones I feed it and that doesn't seem to speed anything up. I don't understand how changing the input values would explode the time complexity, but I also don't understand how Z3 works in general.

I'm rather flummoxed tbh. My logic appears to mirror my friend's Python implementation. FWIW, he fed Python Z3 ~350 stones and got an answer in a reasonable amount of time. My ruby script has been running for 2+ hours with no end in sight.

**Comment by taw** [comment]
The problem with your code is `line.scan(/-?\d+/).map(&:to_f)`. Because you're doing assertions between IntExpr and Float, z3 gem casts both sides to reals, so you end up with:

```
(313743533208081 + (51 * to_real(t0))) = to_real(x + (vx * t0))
(328167831228390 + (115 * to_real(t0))) = to_real(y + (vy * t0))
(159732064722764 + (83 * to_real(t0))) = to_real(z + (vz * t0))
(468183773350185 + (-243 * to_real(t1))) = to_real(x + (vx * t1))
(269960480220160 + (-42 * to_real(t1))) = to_real(y + (vy * t1))
(439515864552130 + (-12 * to_real(t1))) = to_real(z + (vz * t1))
(182013004223519 + (84 * to_real(t2))) = to_real(x + (vx * t2))
(391834672709518 + (-172 * to_real(t2))) = to_real(y + (vy * t2))
(355278372451916 + (15 * to_real(t2))) = to_real(z + (vz * t2))
```

If you change that line to `line.scan(/-?\d+/).map(&:to_i)`, it all works as Python.

**Comment by taw** [comment]
You can debug this kind of issues with `puts solver.assertions`. It will print what exactly your code is asking z3 to do. 

I suspect the python version would have similar issues.

**Comment by taw** [comment]
@Garrett-Bodley Is this solved?

**Comment by Garrett-Bodley** [comment]
Thank you for your help! The package was able to solve the problem in a reasonable amount of time. Changing the inputs to `int` solved the issue.

As an aside: I was confused for a moment as z3 seemed to struggle if I fed it more than 3 input stones, yet my friend was able to feed the entire input into his python solution to get an answer. It turns out that his input made that computationally possible, which was not true for my individual input. Feeding the entirety of my input into his Python solution led to similarly unacceptable time complexity. AoC inputs are weird I guess.

Thank you very much for building this package and helping me figure out how to get it working for AoC!
