### ISSUE TITLE
Installation of Z3 Gem.

### ISSUE THREAD

**Issue by peddivarunkumar** [taw/z3#27]
Gem being shown installed but when trying to use Z3 getting  Load error. Please help.

**Comment by taw** [comment]
What's the OS and error message?

You still need to install z3 library, with `brew install z3`or similar. This gem only provides Ruby interface to whichever version of z3 you installed on your system.

**Comment by peddivarunkumar** [comment]
yes that’s done, i installed Z3 before installing and using the gem.
it worked only when i cloned this repo and copied z3 lib folder into my projects

And hey I am amaze by your work and Z3 algo itself thanks for the examples and all :)

**Comment by peddivarunkumar** [comment]
I am on Ubuntu
