### ISSUE TITLE
Not able to Load Z3?

### ISSUE THREAD

**Issue by peddivarunkumar** [taw/z3#28]
Install the mechanize gem version ~>2.7.5 for using mechanize functions.
[0m[91mDoing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
[0m[91mrake aborted!
LoadError: Could not open library 'libz3.so.4.8': libz3.so.4.8: cannot open shared object file: No such file or directory.
Could not open library 'libz3.so': libz3.so: cannot open shared object file: No such file or directory.
Could not open library 'z3': z3: cannot open shared object file: No such file or directory.
Could not open library 'libz3.so': libz3.so: cannot open shared object file: No such file or directory.
Could not open library 'libz3': libz3: cannot open shared object file: No such file or directory.
Could not open library 'libz3.so': libz3.so: cannot open shared object file: No such file or directory.
Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib
[0m[91m/usr/local/bundle/bundler/gems/ffi-683e18b777a0/lib/ffi/dynamic_library.rb:65:in `load_library'
/usr/local/bundle/bundler/gems/ffi-683e18b777a0/lib/ffi/library.rb:95:in `block in ffi_lib'
/usr/local/bundle/bundler/gems/ffi-683e18b777a0/lib/ffi/library.rb:94:in `map'
/usr/local/bundle/bundler/gems/ffi-683e18b777a0/lib/ffi/library.rb:94:in `ffi_lib'
/usr/src/app/lib/z3/very_low_level.rb:7:in `<module:VeryLowLevel>'
/usr/src/app/lib/z3/very_low_level.rb:5:in `<module:Z3>'
/usr/src/app/lib/z3/very_low_level.rb:4:in `<main>'
/usr/src/app/lib/z3.rb:5:in `require_relative'
/usr/src/app/lib/z3.rb:5:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/usr/src/app/config/initializers/hr_strategy_init.rb:10:in `block in <main>'
/usr/src/app/config/initializers/hr_strategy_init.rb:10:in `each'
/usr/src/app/config/initializers/hr_strategy_init.rb:10:in `<main>'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:667:in `load'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:667:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/notifications.rb:208:in `instrument'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:666:in `load_config_initializer'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:372:in `initialize!'
/usr/src/app/config/environment.rb:5:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:348:in `require_environment!'
/usr/local/bundle/gems/railties-7.0.6/lib/rails/application.rb:506:in `block in run_tasks_blocks'
/usr/local/bundle/gems/bugsnag-6.26.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/usr/local/bundle/gems/bugsnag-6.26.0/lib/bugsnag/integrations/rake.rb:20:in `execute'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:492:in `exec'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
[0m[91mTasks: TOP => environment
[0m[91m(See full trace by running task with --tr

**Comment by taw** [comment]
I tried it on both latest LTS releases of Ubuntu in docker (`docker run -it ubuntu:latest` etc.), it works for me:


```
root@196935070ec2:/# apt update; apt install -y ruby-dev libz3-dev build-essential
[...]
root@196935070ec2:/# gem install z3
Building native extensions. This could take a while...
Successfully installed ffi-1.17.0
Successfully installed z3-0.0.20230311
Parsing documentation for ffi-1.17.0
Installing ri documentation for ffi-1.17.0
Parsing documentation for z3-0.0.20230311
Installing ri documentation for z3-0.0.20230311
Done installing documentation for ffi, z3 after 4 seconds
2 gems installed
root@196935070ec2:/# ruby -e 'require "z3"; puts Z3.version'
4.8.12.0
root@196935070ec2:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Tried it on newer one, still works:

```
root@a8043913c6fa:/# gem install z3
Fetching z3-0.0.20230311.gem
Fetching ffi-1.17.0-x86_64-linux-gnu.gem
Successfully installed ffi-1.17.0-x86_64-linux-gnu
Successfully installed z3-0.0.20230311
Parsing documentation for ffi-1.17.0-x86_64-linux-gnu
Installing ri documentation for ffi-1.17.0-x86_64-linux-gnu
Parsing documentation for z3-0.0.20230311
Installing ri documentation for z3-0.0.20230311
Done installing documentation for ffi, z3 after 0 seconds
2 gems installed
root@a8043913c6fa:/# ruby -e 'require "z3"; puts Z3.version'
4.8.12.0
root@a8043913c6fa:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

Which version are you using?

**Comment by peddivarunkumar** [comment]
Thanks taw it’s working fine now.
