### ISSUE TITLE
Solution differs from EXCEL. The solutin given by Z3 for these set of equations is different from that of EXCEL.

### ISSUE THREAD

**Issue by peddivarunkumar** [taw/z3#29]
a = b
c = 625000-250000 - e - 44150 - 0
d = if( 125000 > c, c, 125000 )
b = if( d < 0, 0, d )
e = l * 12
f = 625000-250000 - a  - 44150
g = if( f <0,0, f)
h = if( a <0,0, g)
i= if( h > f, f , g)
j = if( a <0,0, i)
k = if( j <= 0,0, j)
l = k / 12
m= 250000 + e
n = g / 12

Why the solution is different from EXCEL Solution?

**Comment by taw** [comment]
What's the code that you're using for both?

**Comment by peddivarunkumar** [comment]
Modelled the above equations in both Excel and Z3 in Ruby. Excel returns a different answer from this.

**Comment by taw** [comment]
I can't help you if I don't see the code. Most likely you made a mistake in the code in one of the versions.

**Comment by peddivarunkumar** [comment]
@taw , actually these equations have multiple solutions, and the solution returned by Excel does not match our code.

**Comment by peddivarunkumar** [comment]
from z3 import *

# Define variables
a = Real('a')
b = Real('b')
c = Real('c')
d = Real('d')
e = Real('e')
f = Real('f')
g = Real('g')
h = Real('h')
i = Real('i')
j = Real('j')
k = Real('k')
l = Real('l')
m = Real('m')
n = Real('n')

# Create a solver instance
solver = Solver()

# Add constraints based on the equations

# Equation 1: a = b
solver.add(a == b)

# Equation 2: c = 625000 - 250000 - e - 44150 - 0
solver.add(c == 625000 - 250000 - e - 44150 - 0)

# Equation 3: d = if(125000 > c, c, 125000)
solver.add(d == If(125000 > c, c, 125000))

# Equation 4: b = if(d < 0, 0, d)
solver.add(b == If(d < 0, 0, d))

# Equation 5: e = l * 12
solver.add(e == l * 12)

# Equation 6: f = 625000 - 250000 - a - 44150
solver.add(f == 625000 - 250000 - a - 44150)

# Equation 7: g = if(f < 0, 0, f)
solver.add(g == If(f < 0, 0, f))

# Equation 8: h = if(a < 0, 0, g)
solver.add(h == If(a < 0, 0, g))

# Equation 9: i = if(h > f, f, g)
solver.add(i == If(h > f, f, g))

# Equation 10: j = if(a < 0, 0, i)
solver.add(j == If(a < 0, 0, i))

# Equation 11: k = if(j <= 0, 0, j)
solver.add(k == If(j <= 0, 0, j))

# Equation 12: l = k / 12
solver.add(l == k / 12)

# Equation 13: m = 250000 + e
solver.add(m == 250000 + e)

# Equation 14: n = g / 12
solver.add(n == g / 12)

# Optionally, add non-negativity constraints if variables are expected to be non-negative
variables = [a, b, c, d, e, f, g, h, i, j, k, l, m, n]
for var in variables:
    solver.add(var >= 0)

# Check for solutions
if solver.check() == sat:
    model = solver.model()
    print("Solution:")
    for var in variables:
        print(f"{var} = {model[var]}")
else:
    print("No solution found.")
