### ISSUE TITLE
Function 'Z3_get_smtlib_assumption' not found

### ISSUE THREAD

**Issue by lazzarello** [taw/z3#5]
Looks like the Z3 API changed, hacking... 

Here's my environment info

macOS 10.12.6

```
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]

$ brew info z3
z3: stable 4.6.0 (bottled), HEAD
High-performance theorem prover
https://github.com/Z3Prover/z3
/usr/local/Cellar/z3/4.6.0 (92 files, 82.9MB) *
  Poured from bottle on 2018-02-03 at 12:17:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/z3.rb
```

Here's the output

```
[2] pry(main)> require_relative 'lib/z3'
FFI::NotFoundError: Function 'Z3_get_smtlib_assumption' not found in [libz3.dylib]
from /Users/lazzarello/.gem/ruby/2.5.0/gems/ffi-1.9.18/lib/ffi/library.rb:275:in `attach_function
```

Is the [upstream header file](https://github.com/Z3Prover/z3/blob/master/src/api/z3_api.h) `z3_api.h` the reference for function names?

**Comment by lazzarello** [comment]
Okay, confirmed that file defines the functions and the API has changed quite a bit in the last two years.

[Old line 5016](https://github.com/Z3Prover/z3/blob/a2ecb19d0384e20446138213c1ac7d27081efb94/src/api/z3_api.h#L5016) defines `Z3_get_smtlib_assumption`

[Current line 5016](https://github.com/Z3Prover/z3/blob/master/src/api/z3_api.h#L5016) is some comments.

I guess the next step is to figure out the details of the `api/gen_api` utility and run an update to the API.

**Comment by taw** [comment]
I pushed updated version, none of these functions were used for anything.
There's a minor issue that some of the tests have multiple solutions, so every version breaks a few by choosing a different valid solution.

Now I'm seeing another problem as Integer#coerce seems to be broken in 2.5.0, so I'll bug report that before I come back to z3.

**Comment by taw** [comment]
`gem install z3` should now work, regardless of ruby version, reasonable z3 version, and operating system.

**Comment by taw** [comment]
Closing as it should be fixed. Maybe we need better system for dealing with z3 API changes, but it's fine for now.
